### ISSUE TITLE
Newer API version of cert-manager should be supported

### ISSUE THREAD

**Issue by inductor** [projectcontour/contour-authserver#23]
**What steps did you take and what happened:**

The provided config file has an old version of cert-manager. Ref. https://github.com/projectcontour/contour-authserver/blob/main/config/htpasswd/certificate.yaml

`apiVersion: cert-manager.io/v1alpha3` is old and now we want to use `cert-manager.io/v1`.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Software version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by t4i5uKE** [comment]
Fixed apiVersion of cert-manager to a newer version. #24

**Comment by sunjayBhatia** [comment]
closing via https://github.com/projectcontour/contour-authserver/pull/24
